language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
before_script: pip install -U -r test-requirements.txt --use-mirrors
script: py.test coveralls/tests.py --doctest-modules --pep8 fencepy -v --cov fencepy --cov-report term-missing
after_success: coveralls
